---
- name: build a cloud-init instance
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: setup 
    redhat.satellite.host:
      username: admin
      password: password
      server_url: "https://starfleet.icsa.iad.redhat.com"
      name: "test-init"
      hostgroup: "rhel7"
      compute_resource: tysons_vcenter
      compute_profile: '1-Small'
      state: present
      provision_method: image
      image: img-rhel7-std-server
