---
- name: create new VM
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      esxi_hostname: crusher
      name: "{{ new_vm_name }}"
      template: "{{ template }}"
      datacenter: tysons
      folder: /crusher_ds0/{{new_vm_name}}
      state: poweredon
      wait_for_ip_address: yes
  
