---
- name: create new VM
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: '{{ lookup("env", "VMWARE_HOST") }}'
      username: '{{ lookup("env", "VMWARE_USER") }}'
      password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
      validate_certs: False
      esxi_hostname: crusher.icsa.iad.redhat.com
      name: "{{ new_vm_name }}"
      template: "{{ template }}"
      datacenter: tysons
      state: poweredon
      wait_for_ip_address: yes 
      folder: Demo_VMs
